version: 2
jobs:
  build:
    executorType: docker
    docker:
      - image: hseeberger/scala-sbt
    working_directory: /root/play-async/
    steps:
      - checkout
      - restore_cache:
          name: Restoring Cache
          keys:
            - sbt
      - setup_remote_docker
      - run:
          name: prepare
          command: sbt update exit
      - save_cache:
          name: saving Cache sbt
          key: sbt
          paths:
            - "/root/.sbt"
            - "/root/.ivy2"
      - run:
          name: test
          command:
            sbt test exit

      - deploy:
            name: publish
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ];
                then sbt package publish exit;
              fi

      - store_test_results:
          path:
            target/test-reports